/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type BlogListingPageContentResponseModelContentType = typeof BlogListingPageContentResponseModelContentType[keyof typeof BlogListingPageContentResponseModelContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlogListingPageContentResponseModelContentType = {
  blogListingPage: 'blogListingPage',
} as const;
