/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ApiBlockListModel } from './apiBlockListModel';
import type { RichTextModel } from './richTextModel';

export interface BlogArticlePagePropertiesModel {
  /** @nullable */
  title?: string | null;
  components?: ApiBlockListModel;
  /** @nullable */
  summaryDescription?: string | null;
  richText?: RichTextModel;
}
