/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiContentResponseModelBase } from './iApiContentResponseModelBase';
import type { BlogArticlePageContentModel } from './blogArticlePageContentModel';
import type { BlogArticlePageContentResponseModelContentType } from './blogArticlePageContentResponseModelContentType';

export type BlogArticlePageContentResponseModel = Omit<IApiContentResponseModelBase & BlogArticlePageContentModel, 'contentType'> & {
  contentType: BlogArticlePageContentResponseModelContentType;
};
