/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiElementModelBase } from './iApiElementModelBase';
import type { CodeSnippetComponentPropertiesModel } from './codeSnippetComponentPropertiesModel';
import type { CodeSnippetComponentElementModelContentType } from './codeSnippetComponentElementModelContentType';

export type CodeSnippetComponentElementModel = Omit<IApiElementModelBase, 'contentType'> & {
  properties?: CodeSnippetComponentPropertiesModel;
  contentType: CodeSnippetComponentElementModelContentType;
};
