/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { IApiMediaWithCropsModel } from './iApiMediaWithCropsModel';

export interface CompositionPageMetaDataPropertiesModel {
  /** @nullable */
  metaTitle?: string | null;
  /** @nullable */
  metaDescription?: string | null;
  /** @nullable */
  hideFromSearch?: boolean | null;
  /** @nullable */
  metaKeywords?: string | null;
  /** @nullable */
  canonicalLinkUrl?: string | null;
  /** @nullable */
  openGraphLabel?: string | null;
  /** @nullable */
  enableOpenGraph?: boolean | null;
  /** @nullable */
  openGraphType?: string | null;
  /** @nullable */
  openGraphTitle?: string | null;
  /** @nullable */
  openGraphDescription?: string | null;
  /** @nullable */
  openGraphImage?: IApiMediaWithCropsModel[] | null;
}
