/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ImageComponentElementModel } from './imageComponentElementModel';
import type { QuoteComponentElementModel } from './quoteComponentElementModel';
import type { RichTextComponentElementModel } from './richTextComponentElementModel';
import type { CodeSnippetComponentElementModel } from './codeSnippetComponentElementModel';

export type IApiElementModel = ImageComponentElementModel | QuoteComponentElementModel | RichTextComponentElementModel;
