/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { BlogArticlePageContentResponseModel } from './blogArticlePageContentResponseModel';
import type { BlogListingPageContentResponseModel } from './blogListingPageContentResponseModel';
import type { HomePageContentResponseModel } from './homePageContentResponseModel';

export type IApiContentResponseModel = BlogArticlePageContentResponseModel | BlogListingPageContentResponseModel | HomePageContentResponseModel;
