/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type RichTextComponentElementModelContentType = typeof RichTextComponentElementModelContentType[keyof typeof RichTextComponentElementModelContentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RichTextComponentElementModelContentType = {
  richTextComponent: 'richTextComponent',
} as const;
