// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetContentData, GetContentResponse, GetContentError, GetContent20Data, GetContent20Response, GetContent20Error, GetContentItemData, GetContentItemResponse, GetContentItemByPathData, GetContentItemByPathResponse, GetContentItemByPath20Data, GetContentItemByPath20Response, GetContentItemByIdData, GetContentItemByIdResponse, GetContentItemById20Data, GetContentItemById20Response, GetContentItems20Data, GetContentItems20Response, GetMediaData, GetMediaResponse, GetMediaError, GetMedia20Data, GetMedia20Response, GetMedia20Error, GetMediaItemData, GetMediaItemResponse, GetMediaItemByPathData, GetMediaItemByPathResponse, GetMediaItemByPath20Data, GetMediaItemByPath20Response, GetMediaItemByIdData, GetMediaItemByIdResponse, GetMediaItemById20Data, GetMediaItemById20Response, GetMediaItems20Data, GetMediaItems20Response } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * @deprecated
 */
export const getContent = <ThrowOnError extends boolean = false>(options?: Options<GetContentData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetContentResponse, GetContentError, ThrowOnError>({
        url: '/umbraco/delivery/api/v1/content',
        ...options
    });
};

export const getContent20 = <ThrowOnError extends boolean = false>(options?: Options<GetContent20Data, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetContent20Response, GetContent20Error, ThrowOnError>({
        url: '/umbraco/delivery/api/v2/content',
        ...options
    });
};

/**
 * @deprecated
 */
export const getContentItem = <ThrowOnError extends boolean = false>(options?: Options<GetContentItemData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetContentItemResponse, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v1/content/item',
        ...options
    });
};

/**
 * @deprecated
 */
export const getContentItemByPath = <ThrowOnError extends boolean = false>(options: Options<GetContentItemByPathData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetContentItemByPathResponse, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v1/content/item/{path}',
        ...options
    });
};

export const getContentItemByPath20 = <ThrowOnError extends boolean = false>(options: Options<GetContentItemByPath20Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetContentItemByPath20Response, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v2/content/item/{path}',
        ...options
    });
};

/**
 * @deprecated
 */
export const getContentItemById = <ThrowOnError extends boolean = false>(options: Options<GetContentItemByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetContentItemByIdResponse, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v1/content/item/{id}',
        ...options
    });
};

export const getContentItemById20 = <ThrowOnError extends boolean = false>(options: Options<GetContentItemById20Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetContentItemById20Response, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v2/content/item/{id}',
        ...options
    });
};

export const getContentItems20 = <ThrowOnError extends boolean = false>(options?: Options<GetContentItems20Data, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetContentItems20Response, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v2/content/items',
        ...options
    });
};

/**
 * @deprecated
 */
export const getMedia = <ThrowOnError extends boolean = false>(options?: Options<GetMediaData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMediaResponse, GetMediaError, ThrowOnError>({
        url: '/umbraco/delivery/api/v1/media',
        ...options
    });
};

export const getMedia20 = <ThrowOnError extends boolean = false>(options?: Options<GetMedia20Data, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMedia20Response, GetMedia20Error, ThrowOnError>({
        url: '/umbraco/delivery/api/v2/media',
        ...options
    });
};

/**
 * @deprecated
 */
export const getMediaItem = <ThrowOnError extends boolean = false>(options?: Options<GetMediaItemData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMediaItemResponse, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v1/media/item',
        ...options
    });
};

/**
 * @deprecated
 */
export const getMediaItemByPath = <ThrowOnError extends boolean = false>(options: Options<GetMediaItemByPathData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetMediaItemByPathResponse, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v1/media/item/{path}',
        ...options
    });
};

export const getMediaItemByPath20 = <ThrowOnError extends boolean = false>(options: Options<GetMediaItemByPath20Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetMediaItemByPath20Response, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v2/media/item/{path}',
        ...options
    });
};

/**
 * @deprecated
 */
export const getMediaItemById = <ThrowOnError extends boolean = false>(options: Options<GetMediaItemByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetMediaItemByIdResponse, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v1/media/item/{id}',
        ...options
    });
};

export const getMediaItemById20 = <ThrowOnError extends boolean = false>(options: Options<GetMediaItemById20Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetMediaItemById20Response, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v2/media/item/{id}',
        ...options
    });
};

export const getMediaItems20 = <ThrowOnError extends boolean = false>(options?: Options<GetMediaItems20Data, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMediaItems20Response, unknown, ThrowOnError>({
        url: '/umbraco/delivery/api/v2/media/items',
        ...options
    });
};